version: "3.9"
services:
  php:
    container_name: laravel-php
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - .:/var/www
    working_dir: /var/www
    depends_on:
      - mysql

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - php



  mysql:
    image: mysql:8
    container_name: laravel-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
